server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://${CONFIG_SERVER_USERNAME:config_admin}:${CONFIG_SERVER_PASSWORD:config_pass}@${CONFIG_SERVER_HOST:config-server}:8888
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/files/**
        - id: user-profile-service
          uri: lb://user-profile-service
          predicates:
            - Path=/api/users/**
        - id: auth-service-docs
          uri: lb://auth-service
          predicates:
            - Path=/v3/api-docs/auth-service
          filters:
            - RewritePath=/v3/api-docs/auth-service, /v3/api-docs
        - id: file-service-docs
          uri: lb://file-service
          predicates:
            - Path=/v3/api-docs/file-service
          filters:
            - RewritePath=/v3/api-docs/file-service, /v3/api-docs
        - id: user-profile-service-docs
          uri: lb://user-profile-service
          predicates:
            - Path=/v3/api-docs/user-profile-service
          filters:
            - RewritePath=/v3/api-docs/user-profile-service, /v3/api-docs
        - id: notification-service-docs
          uri: lb://notification-service
          predicates:
            - Path=/v3/api-docs/notification-service
          filters:
            - RewritePath=/v3/api-docs/notification-service, /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:admin_pass}@${EUREKA_HOST:eureka-server}:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    persist-authorization: true
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /v3/api-docs/auth-service
      - name: file-service
        url: /v3/api-docs/file-service
      - name: user-profile-service
        url: /v3/api-docs/user-profile-service
      - name: notification-service
        url: /v3/api-docs/notification-service
    urls-primary-name: auth-service
