spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379
      password: ${REDIS_PASSWORD:redis_pass}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

auth-service:
  validate-url: http://auth-service/api/auth/validate

rate-limit:
  requests-per-minute: 100
