spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgresql}:5432/user_db
    username: ${POSTGRES_USER:platform_user}
    password: ${POSTGRES_PASSWORD:platform_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
        hbm2ddl.create_namespaces: true
  flyway:
    enabled: true
    schemas: public
    default-schema: public
    create-schemas: true
    baseline-on-migrate: true
    baseline-version: 0
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:rabbit_user}
    password: ${RABBITMQ_DEFAULT_PASS:rabbit_pass}

feign:
  client:
    config:
      file-service:
        connectTimeout: 5000
        readTimeout: 30000
