server:
  port: 8888

spring:
  application:
    name: config-server
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:config_admin}
      password: ${CONFIG_SERVER_PASSWORD:config_pass}
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs/

  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:admin_pass}@eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
